### ISSUE TITLE
Feature - Main page CSS

### ISSUE THREAD

**Issue by DanielVolchek** [multiverse-circuit-breakers/inventory-app#15]
asignee: X

## User story
Users should have an appealing view of the page with the website on it. It should feature a clean header with a button that redirects to the home page view, the items in a well arranged flexbox, and the add button in a prominent location.

## Implementation
Put items in flexbox
Make button look nice
¯\\_(ツ)_/¯

**Comment by tanicha** [comment]
Starting on putting items in flex box and creating a home page layout for all items to be shown

**Comment by tanicha** [comment]
main page css completed.
